# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
            options={
                'verbose_name': 'Some Child',
                'verbose_name_plural': 'Some Childs',
            },
        ),
        migrations.CreateModel(
            name='SomeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('editor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeable_objects', to='auth.Group', verbose_name='Editor Group')),
                ('viewer_groups', models.ManyToManyField(blank=True, related_name='visible_objects', to='auth.Group', verbose_name='Viewer Groups')),
            ],
            options={
                'verbose_name': 'Some Object',
                'verbose_name_plural': 'Some Objects',
                'permissions': (('one', 'one'), ('two', 'two'), ('two_two', 'two two'), ('three_someobject', 'three'), ('four_some_object', 'four')),
            },
        ),
        migrations.AddField(
            model_name='somechild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='someapp.SomeObject', verbose_name='Parent'),
        ),
    ]
